[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  publish = "."
  autoLaunch = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
